---
abstract: 'Atom feed and API implementation'
author:
  - 'Benjamin Trott, Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.17, Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Atom
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Class::Data::Inheritable: '0'
  DateTime: '0'
  DateTime::TimeZone: '0'
  Digest::SHA1: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  URI: '0'
  XML::LibXML: '1.69'
  XML::XPath: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/xml-atom/issues
  homepage: https://github.com/miyagawa/xml-atom
  repository: https://github.com/miyagawa/xml-atom.git
version: '0.42'
x_contributors:
  - 'Andreas Marienborg <andreas.marienborg@gmail.com>'
  - 'Benjamin Trott <ben@stupidfool.org>'
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'Dave Cross <dave@dave.org.uk>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'emasaka <emasaka@gmail.com>'
  - 'Jonathan "Duke" Leto <jonathan@leto.net>'
  - 'Martin Atkins <mart@degeneration.co.uk>'
  - 'root <root@localhost.localdomain>'
  - 'Simon Wistow <simonw@cpan.org>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
  - 'Vince Veselosky <vince@control-escape.com>'
  - 'Yann Kerherve <yann@cyberion.net>'
x_serialization_backend: 'YAML::Tiny version 1.70'
