abstract: Atom API and Feed Support
author: Benjamin Trott <cpan@stupidfool.org>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: XML-Atom
no_index: 
  directory: 
    - t
    - inc
    - t
recommends: 
  DateTime: 0
  Digest::SHA1: 0
  HTML::Parser: 0
  LWP: 0
  LWP::Authen::Wsse: 0
  XML::LibXML: 1.54
  XML::XPath: 0
requires: 
  Class::Data::Inheritable: 0
  MIME::Base64: 0
  URI: 0
version: 0.21_02
