name: XML-Atom
version: 0.15
abstract: Atom API and Feed Support
author: Benjamin Trott <cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  XML::LibXML: 1.54
  MIME::Base64: 0
  URI: 0
recommends:
  LWP: 0
  LWP::Authen::Wsse: 0
  Digest::SHA1: 0
  DateTime: 0
  HTML::Parser: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.34
